### ISSUE TITLE
expose cursor position?

### ISSUE THREAD

**Issue by wmhilton** [satya164/react-simple-code-editor#15]
Would it be easy to expose the cursor position as well? Perhaps as a `onCursorChange` prop?
I need to know when the cursor is on the very first or very last line of a file.

**Comment by satya164** [comment]
Can't you do it with `document.addEventListener('selectionchange')`? Closing this since it seems unnecessary.

**Comment by chug2k** [comment]
since this is react, wouldn't we need a `ref` to the underlying `textarea`?
