### ISSUE TITLE
CSS needed for example code highlighting to work

### ISSUE THREAD

**Issue by macduff111** [satya164/react-simple-code-editor#16]
Hi
your example needs the prism css for highlighting to work
ie add the line
`import 'prismjs/themes/prism.css'`

**Comment by satya164** [comment]
It's mentioned in the README that you might need to import some CSS https://github.com/satya164/react-simple-code-editor/blob/master/README.md#usage

**Comment by FateRiddle** [comment]
@satya164 So show the whole working demo, with any syntax theme really. What does a half ass demo do for anyone?

**Comment by satya164** [comment]
@FateRiddle maybe you'd find the full ass demo in the example folder if you spent 2 minutes looking in the project instead of being rude on GitHub issues.

**Comment by FateRiddle** [comment]
@satya164 I was rude because I find your answer to a legit question passively aggressive and not helpful. 
People using this editor may not want to style it all by themselves but also prefer a wide range of theme choices. So a custom styled example might not be a perfect answer.

**Comment by satya164** [comment]
@FateRiddle how is linking to the docs passive aggressive? it's an open source project and I work on it on my free time. I don't have time to write detailed answer to every github issue. if my answer is not satisfying to you, feel free to send PR to improve the README or answer in issues. anyway, that doesn't mean you should be rude.

regardless, this library doesn't do syntax highlighting. it only renders a text area over your syntax highlighted code. you can use prism or any other library you want. how you make syntax highlighting work is outside the scope of this library. if you're setting up prism, you need to follow prism docs for that, or any docs of the lib you're using. this is already mentioned in README. but if it's not clear, then PR welcome to make it more clearer.
