### ISSUE TITLE
ability to prevent keyDown handler logic

### ISSUE THREAD

**Issue by tj** [satya164/react-simple-code-editor#17]
Thanks for this lib! 

I'm looking to prevent the default functionality from inserting a newline when the user types `cmd+enter`, in order to submit a query with the editor's value. I'm not sure how that would be best handled actually, but opening an issue in case you'd be cool with it, possibly feature-creeping.

**Comment by tj** [comment]
works for me! that'd be great

**Comment by satya164** [comment]
Do you wanna send a PR? 😅
