### ISSUE TITLE
Consider enforcing overflow-wrap

### ISSUE THREAD

**Issue by kizu** [satya164/react-simple-code-editor#26]
### Current behaviour

I have tested a long string (like `mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm`) at the demo — and it doesn't work due to the styles you're using there for the container.

### Expected behaviour

In my opinion, both textarea and the `<pre>` for the code should have an `overflow-wrap` etc. enforced to a `break-word` as in some browsers other values cannot be set for a textarea, leading to the misalign of the visual representation of the code and the text itself.

### Proposed solution.

This behaviour works from the box at the codesandbox, but as seen at the demo it is very easy to shoot yourself in the leg and enable the bad behaviour, so I think the values for `white-space`, `word-break` and `overflow-wrap` shouldn't be inherited, but should be set to the ones that work for most cases (`white-space` could have also different effects for regular elements and text inside textarea from what I remember).

**Comment by satya164** [comment]
@kizu hey, it was actually fixed in https://github.com/satya164/react-simple-code-editor/pull/24, but I forgot to update the demo

**Comment by kizu** [comment]
Cool! However, I think it would still could be helpful to disallow setting those properties by setting them on the elements themselves and not by inheriting them?

Here is an example: https://codesandbox.io/s/62mqv9v8j3 — at least in Chrome you could see that it doesn't work properly.

**Comment by satya164** [comment]
@kizu yeah, fair enough. do you want to send a PR?

**Comment by kizu** [comment]
I'll consider it, would try to do it when I'll get a bit of free time :)
