### ISSUE TITLE
Cannot insert tab characters

### ISSUE THREAD

**Issue by jonsilvacodes** [satya164/react-simple-code-editor#29]
### Current behaviour
In an editor with prop `insertSpaces={false}` and `tabSize={1}`, pressing the tab key inserts 5 spaces.

### Expected behaviour
In an editor with prop `insertSpaces={false}` and `tabSize={1}`, pressing the tab key *should* insert a tab character.

### Possible cause
I think that this is because of an error on line 256 of index.js where 5 spaces are used instead of a literal tab character
    <pre>`const tabCharacter = (insertSpaces ? ' ' : '     ').repeat(tabSize);`</pre>

### Your Environment
For reference, I am using version 0.9.4 from npm.

I would be happy to submit a PR replacing the spaces with a tab character.

**Comment by satya164** [comment]
Oops. Seems like a mistake. Yeah, would be great if you can send a PR.

**Comment by satya164** [comment]
Fixed in 394c15969db150c2d04ee222ba364cb95988e929
