### ISSUE TITLE
Missing line number

### ISSUE THREAD

**Issue by o2sh** [satya164/react-simple-code-editor#30]
Great work !

Only thing missing is line numbering.

Are you planning to add this feature ?

thanks

**Comment by satya164** [comment]
You can do it in your code: https://github.com/satya164/react-simple-code-editor/commit/809d5f042637918dc41524ab40ec1d1d581e335d

**Comment by FateRiddle** [comment]
@satya164 Thanks for the solution, but the usage is still not obvious for most users. I'd be appreciated if you could just add that functionality as props.

**Comment by satya164** [comment]
this solution highly depends on how you perform syntax highlighting etc. I can't add it in core because we don't control the HTML generated after syntax highlighting.

**Comment by so2liu** [comment]
> @satya164 Thanks for the solution, but the usage is still not obvious for most users. Also when I tried it out, I find you may need to change the code:
> 
> ```js
>  line =>`<span class="container_editor_line_number">${line}</span>`
> ```
> 
> to
> 
> ```js
>  line =>`<span class="container_editor_line_number"><span>${index+1}</span><span>${line}</span></span>`
> ```
> 
> And even after this, the styling can be tricky, because if the code line wraps, it won't leave the white space for line number and just starting from very left.
> 
> Also selection of code will work weirdly as if the code is still in its original place without the addition of line numbers (at least that happens to my code)
> 
> I'd be appreciated if you could just add that functionality as props.

this way when you copy the code, you will copy the line number, too
