### ISSUE TITLE
how to limit height?

### ISSUE THREAD

**Issue by jschuler** [satya164/react-simple-code-editor#32]
I'd like to limit the height of the Editor container and have the user scroll if they want to edit content further down. I tried by setting a `max-height` and `overflow: auto` but the problem i have is that the textarea scrolls out of view.

Problem illustrated here:
https://codesandbox.io/s/lyp85pkyrq

Any idea how i can vertically limit the height?

**Comment by satya164** [comment]
Wrap the editor in a div with a height instead if setting it on the editor

**Comment by jschuler** [comment]
Thank you!

**Comment by hemavidal** [comment]
I just want to make the editor with a fixed size even with the content is empty. How would I do that?
![image](https://user-images.githubusercontent.com/1553814/70460078-48f94880-1a94-11ea-8799-36b0827afa9e.png)

**Comment by felixge** [comment]
@hemavidal I was able to make this work by passing a `minHeight` attribute to the Editor props that has the same value as the `height` passed to the outer div as suggested by @satya164 .
