### ISSUE TITLE
Line numbers CSS solution doesn't work since 0.9.2

### ISSUE THREAD

**Issue by hudochenkov** [satya164/react-simple-code-editor#42]
### Current behaviour

Since 0.9.2 (and [this commit](https://github.com/satya164/react-simple-code-editor/commit/d00da98a59f71a5a184caee2ed98be5bec4277da) and [this commit](https://github.com/satya164/react-simple-code-editor/commit/56a12db451ac52a0823d38a3d05549504b123d7f)) it's impossible to add line numbers as it was suggested in https://github.com/satya164/react-simple-code-editor/issues/30#issuecomment-484722824 (https://github.com/satya164/react-simple-code-editor/commit/809d5f042637918dc41524ab40ec1d1d581e335d). Actually, markup is there, but `overflow: hidden` prevents line numbers from showing.

Before mentioned commit, there were no `overflow: hidden` and it was possible to put line numbers outside container with CSS.

### Expected behaviour

Not apply `overflow: hidden` to container.

### Code sample

https://stylelint.io/demo

Line numbers for code area and config area applied via Prism:

https://github.com/stylelint/stylelint-demo/blob/6988cac4f5bcf01999de2234193e212121ad03ee/src/common/linter/index.js#L51-L57

### What have you tried

I tried to use `padding` option, but it supports only one number, and we'll need to use something like `padding: 10px 10px 10px 65px` to style properly.

`style={{ padding: '10px 10px 10px 65px' }}` doesn't work, because `<textarea>` and `<pre>` won't be aligned anymore.

### Your Environment

| software                 | version
| -------------------------| -------
| react-simple-code-editor | 0.9.14
| react                    | 16.9.0

**Comment by ludovicmnji** [comment]
Any solution to solve this ? Can we help to find a solution ?

**Comment by bogutski** [comment]
https://codesandbox.io/s/charming-moore-wy240?fontsize=14&hidenavigation=1&theme=dark

**Comment by hudochenkov** [comment]
Thanks, @bogutski!

**Comment by Dror-Bar** [comment]
@bogutski 
That works if user press "Enter".
What if he writes a long line that breaks? this solution doesn't work if that happens.

**Comment by spino17** [comment]
https://codesandbox.io/s/charming-moore-wy240?fontsize=14&hidenavigation=1&theme=dark This works well in firefox and chrome but has weird overlap of line number 1 and 2 element
