### ISSUE TITLE
Syntax highlighting does't work

### ISSUE THREAD

**Issue by sandrig** [satya164/react-simple-code-editor#46]
react-simple-code-editor: "0.9.15"
prismjs: "1.17.1"

Example: https://codesandbox.io/embed/infallible-surf-vuhdn

**Comment by derozn** [comment]
So the part that the documentation about the demo that is missing is the CSS that controls the syntax highlighting. In the demo starting from L86 https://github.com/satya164/react-simple-code-editor/blob/master/example/styles.css#L86 there are CSS selector rules that control the markup returned by prismjs. You can either choose to do this yourself **or** choose a pre-defined theme yourself by importing from the `prismjs/themes/` folder.

For example `import 'prismjs/themes/prism.css'`

**Comment by sandrig** [comment]
Thanks! It works now.

**Comment by madhu131313** [comment]
@satya164  can you please add about example import statement of css in readme. I had to debug for an hour to find out what's missing and finally found a solution here
