### ISSUE TITLE
[Bug] Cursor showing on the wrong letter on chrome

### ISSUE THREAD

**Issue by GiardEmilien** [satya164/react-simple-code-editor#55]
### Current behaviour

I discovered it on my project but you can have it on the [demo](http://satya164.xyz/react-simple-code-editor/) with chrome.
The cursor is printed on the wrong character. When you type a char, it is added at a position other than the cursor.

### Expected behaviour

I would like my cursor on the right char.

### Code sample

Try to copy paste this code on the demo and then enter a char at the end
```
import React from "react";
import ReactDOM from "react-dom";

function App() {
  return (
    <h1>Hello world</h1>
  );
}

ReactDOM.render(<App />, document.getElementById("root" 
  function ( test

```
### Screenshots (if applicable)

<img width="1171" alt="Capture d’écran 2020-02-11 à 13 55 12" src="https://user-images.githubusercontent.com/37068960/74238609-70f46a80-4cd6-11ea-866a-ee72984ae04f.png">

### What have you tried

I try changing css attributes on class editor but didn't successfully fixed the issue
### Your Environment
You can use the same as the one used by the demo but mine is:
| software                 | version
| -------------------------| -------
| react-simple-code-editor | 0.11.0
| react                   | 16.12.0 
| npm            | 6.13.4  
| node                   | 10.15.3 
| browser       chrome (mac OS)           |  80.0.3987.87

**Comment by kitten** [comment]
> When you type a char, it is added at a position other than the cursor.

I think you may want to add more details on how to _reproduce_ this. I've just taken a look and the demo still works fine for me and as expected.

`react-simple-code-editor` works by keeping a texteditor and a div in sync with the same content and formatting, so if they're not in sync, the cursor won't be in sync. But I think in this case this issue will need more details on how to reproduce this.

**Comment by GiardEmilien** [comment]
@kitten Thanks for looking at my issue.
The bug only occurs on Chrome and it seams the bug does not appear when copy-pasting.
Can you try going to the demo, at the end of the last line type " function" then enter like 20 spaces (enough to fill the line) then type a char. It pops after the cursor.
I have tried it on a coworker's laptop and the bug showed.
As you can see on the screenshot below, I have type the char "d" and it did not print at the cursor (the cursor is at the beginning of the line):
<img width="1171" alt="Capture d’écran 2020-02-11 à 16 26 53" src="https://user-images.githubusercontent.com/37068960/74250812-77411180-4ceb-11ea-9b6d-e9e5c095b9ab.png">
