### ISSUE TITLE
How do I use CSS prism themes?

### ISSUE THREAD

**Issue by elevatebart** [satya164/react-simple-code-editor#56]
### Current behaviour

When I use [vsc-dark-plus](https://github.com/PrismJS/prism-themes/blob/master/themes/prism-vsc-dark-plus.css), I can make sure that all torkens have the proper color except for the background.

### Expected behaviour

May this line be removed?

https://github.com/satya164/react-simple-code-editor/blob/73b57bf4d548257890f9ed0ee83ee37ec099b256/src/index.js#L625

### Code sample
```jsx
require('./prism-vsc-dark-plus.css')
export default function Editor(){
  return <SimpleEditor
				value={'<Button />'}
				highlight={highlight(isVueSFC ? 'html' : 'jsx')}
				// Padding should be passed via a prop (not CSS) for a proper
				// cursor position calculation
				padding={space[2]}
				// to make sure the css styles for prism are taken into account
				preClassName={'language-jsx'}
			/>
}
```

### Screenshots (if applicable)

<img width="1032" alt="Capture d’écran 2020-02-16 à 6 40 23 PM" src="https://user-images.githubusercontent.com/5592465/74616142-d20faa00-50eb-11ea-8a2f-493bf0fc732c.png">

### Sandbox

https://codesandbox.io/s/suspicious-flower-5rl8e

### Your Environment

| software                 | version
| -------------------------| -------
| react-simple-code-editor | 0.11.0
| react                    | 16
| npm or yarn              | yarn
| node                     | 11
| browser                  | Firefox & Chrome

**Comment by elevatebart** [comment]
I have a workaround but it's one my user would prefer to avoid. Add `!important` on the background of the style.

**Comment by satya164** [comment]
The background is set to none because without it the cursor in the textarea below will be covered by the background and won't be visible. You need to set the background color on the container instead of the `pre`.

**Comment by elevatebart** [comment]
the container has no css specifics... I guess I will have to git it one.

**Comment by elevatebart** [comment]
Thank you for the tip, it works super-well

**Comment by SeongwoonHong** [comment]
@elevatebart would you be able to share how you are able to solve it in more details please :)
