### ISSUE TITLE
Mention in readme about syntax highlighting

### ISSUE THREAD

**Issue by UsulPro** [satya164/react-simple-code-editor#6]
Hi! Thank you for this project! :smiley: 

Just wanted to note that possibly it's worth to mention in the readme that to make the listed example to be with syntax highlighted it's necessary to add these styles to your project:

https://github.com/satya164/react-simple-code-editor/blob/11e8ce04ec5e59158bc06d2f14525643e2b2f753/example/styles.css#L72-L131

**Comment by satya164** [comment]
Hey, not necessarily this CSS, but yeah, we should document that you will need to the CSS for the prismjs theme you want when you're using it.

**Comment by satya164** [comment]
Closing since it's now mentioned in the README:

> Note that depending on your syntax highlighter, you might have to include additional CSS for syntax highlighting to work.
