### ISSUE TITLE
Scrolling works only on Highlighted texts

### ISSUE THREAD

**Issue by jungRoit** [satya164/react-simple-code-editor#60]
### Current behaviour
I'm using react-simple-code-editor along with prism for highlighting.

when scrolling, only the highlighted parts are scrolled.
the scroll in not working when i type something but when I select all texts and scroll only the highlighted texts are scrolled and it overlaps the text.

### Expected behaviour
I expect the Scroll to work smoothly and not to overlap contents.

### Code sample
Component

`<React.Fragment>
                <div>
                    <Editor
                        value={this.state.cssCode}
                        onValueChange={this.onValueChange}
                        highlight={cssCode => highlight(cssCode, languages.css)}
                        padding={10}
                        className="editor-container"
                        tabSize={4}
                    />
                </div>
            </React.Fragment>`

Style
`.editor-container {
  border: 1px solid #dfe2e6;
  height: 100px;
  background-color: #fff;
  margin-bottom: 10px;
  padding: 10px 12px;
  border-radius: 6px;
  letter-spacing: 2px;
  overflow: auto;
  padding-right: 23px;
  width: calc(100% - 24px);
  margin-left: 8px;
  margin-right: 8px;
}`

### Your Environment

| software                 | version
| -------------------------| -------
| react-simple-code-editor | 0.10.0
| react                    | 16.9.0
| npm or yarn              | 1.21.1
| node                     | 12.13.0
| browser                  | Chrome

**Comment by Hartha-aloufi** [comment]
Hello

I'm facing the same problem, did you solve it ?

**Comment by Hartha-aloufi** [comment]
for any one who counter this problem, Just don't set the height and the overflow directly to the editor.

**Comment by lesimoes** [comment]
> for any one who counter this problem, Just don't set the height and the overflow directly to the editor.

Works for me, I set min and max height in grid (material ui) outside of component. Thanks

**Comment by chriszirkel** [comment]
Yes, wrap the editor around a `div` and set height and overflow:

`              <div style={{  width: '100%', height: '100%', overflow: 'auto' }}>
`
