### ISSUE TITLE
User-select cant be disabled

### ISSUE THREAD

**Issue by manuelc2209** [satya164/react-simple-code-editor#8]
### Current behaviour

User-selection can't be disabled or changed

### Expected behaviour

Disabling user-selection since when you select the text area it renders the textarea and the wrapper.

### Screenshots (if applicable)

![customarea](https://user-images.githubusercontent.com/20400660/47164381-d9eced80-d2ef-11e8-9b74-be08b4b1f2f1.JPG)

thanks, good job on this lib

**Comment by satya164** [comment]
thanks for the report! can you send a PR?

**Comment by satya164** [comment]
Isn't `user-select: none` enough on the textarea? What's the issue?

**Comment by kitten** [comment]
@satya164 Wouldn't `user-select` have to be applied to both `pre` and `textarea`? Might be simple enough to set it to `inherit` on both, so that the container can receive `user-select` and can pass it on to both

**Comment by satya164** [comment]
@kitten you would still want the user to be able to select the text, so we wouldn't want to disable it on both. from reading again, I think the issue here is on IE, where it's changing the color of the hidden input text on selection.

I think we'd need to do something like this for IE:

```css
.editor::selection  {
  color: transparent;
  background-color: blue;
}
```

**Comment by manuelc2209** [comment]
Will test it and report back, did you find the issue? It wasnt working
before

A sexta, 19/10/2018, 14:22, Satyajit Sahoo <notifications@github.com>
escreveu:

**Comment by satya164** [comment]
@manuelc2209 I have tested it on IE and it is now working fine for me. Please take a look at master when you have time and lemme know if it works for you.

**Comment by manuelc2209** [comment]
Thanks a lot bud, will do asap

Keep up the good work m8

Na(o) sexta, 2/11/2018, 03:11, Satyajit Sahoo <notifications@github.com>
escreveu:
