### ISSUE TITLE
Uncaught ReferenceError: global is not defined | React Typescript

### ISSUE THREAD

**Issue by Gers2017** [satya164/react-simple-code-editor#86]
### Current behaviour
Getting an ``` Uncaught ReferenceError ``` while using react-typescript and [vitejs](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)

### Expected behaviour
The code editor should appear
```
Uncaught ReferenceError: global is not defined
    at node_modules/react-simple-code-editor/lib/index.js (index.js:69)
    at __require (chunk-AABLTR74.js?v=dbc0ac6b:2)
    at dep:react-simple-code-editor:1
node_modules/react-simple-code-editor/lib/index.js @ index.js:69
__require @ chunk-AABLTR74.js?v=dbc0ac6b:2
(anonymous) @ dep:react-simple-code-editor:1
```

### Code sample
```jsx
import React, { useState } from "react";
import logo from "./logo.svg";
import Editor from "react-simple-code-editor";
import { highlight, languages } from "prismjs";
import 'prismjs/components/prism-clike';
import 'prismjs/components/prism-javascript';
import "prismjs/themes/prism.css"; //Example style, you can use another

function App() {
  const [code, setCode] = useState(`function add(a, b) {\n  return a + b;\n}`);

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
      </header>
      <Editor
        value={code}
        onValueChange={(code) => setCode(code)}
        highlight={(code) => highlight(code, languages.js, "javascript")}
        padding={10}
        style={{
          fontFamily: '"Fira code", "Fira Mono", monospace',
          fontSize: 12,
        }}
      />
    </div>
  );
}

export default App;

```

### What have you tried

I have installed @types/prismjs and restarted the app

### Your Environment

| software                 | version
| -------------------------| -------
| react-simple-code-editor | 0.11.0
| react                    | 17.0.0
| npm or yarn              | v1.22.10
| node                     | v14.16.1
| browser                  | brave

**Comment by ruifortes** [comment]
It has to do with global this being renamed to globalThis
Meanwhile just add "<script>const global = globalThis;</script>" to the html file.

**Comment by trishantpahwa** [comment]
Godmode!

> It has to do with global this being renamed to globalThis Meanwhile just add "<script>const global = globalThis;</script>" to the html file.

**Comment by melsayedgit** [comment]
> <script>const global = globalThis;</script>

when i use this fix another error pops up and say process not defined

**Comment by taniaholst** [comment]
> I was getting the same error while working with `react-joyride` with vitejs...
> 
> This error
> 
> ```
> react-dom.development.js:22839 Uncaught ReferenceError: global is not defined
> ```
> 
> @zirkelc 's solution solved it... Thanks

I have the same problem using `react-joyride` with `vitejs`, but with @zirkelc 's solution, I get the following error:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/21334782/233612124-d1d3d8e5-2c17-44e0-8fce-5a878c85520a.png">
