### ISSUE TITLE
Ability to set the textarea id attribute 

### ISSUE THREAD

**Issue by davidjamesstone** [satya164/react-simple-code-editor#9]
It would be nice to be able to set the `id` of the generated textarea, like we can for the `name` and others. I need this to be able to get a `<label for='myid'>...</label>` element to auto focus onto the textarea when clicked.

Great little code editor BTW. It's very useful to have a lightweight option for React.

**Comment by oliveiraddb** [comment]
Another nice to have prop is placeholder. The textarea element has it built-in but I can't seen to be able to set it though simple code editor.

**Comment by satya164** [comment]
@davidjamesstone maybe you could do this instead:

```js
<label>
This is some label
<Editor />
</label>
```

IMO IDs don't play very well with component-based designs because they need to be unique.

@oliveiraddb can you send a PR adding the prop? note that you'll also need to add the following CSS for the placeholder to showup.

```css
.editor textarea:empty {
  -webkit-text-fill-color: initial !important;
}
```

**Comment by davidjamesstone** [comment]
@satya164 Implicit labels wont work in my case as they break the css/layout which I have no control over. They also aren't as well supported as explicit labels in assistive / accessible tooling.

I agree about IDs being kind of at odds with component based design but I don't have an alternative here.

**Comment by satya164** [comment]
@davidjamesstone Okies! I sent a PR adding a prop for that. Lemme know if it works for you.

**Comment by davidjamesstone** [comment]
Looks good & Thank you!

**Comment by kitten** [comment]
See #13 and #14 around how we'd like to avoid preventing more customisation in the future :) It's becoming apparent that every time someone discovers some smaller prop issues or sth they need to customise, they hit a wall and need a fix in the main lib, so customisability would be a neater answer ✨

**Comment by davidjamesstone** [comment]
Thanks @satya164. Much appreciated.

**Comment by satya164** [comment]
Actually this prop isn't released. I just added placeholder prop. Will support id with render props later.
